
# The directory that contains all the content
title: xyDocs
content_dir: D:\Test\Docs\Dokumenter
# content_dir: P:\Dokumenter


#################
# Optional settings:

theme:
  - Wiki
  - Wiki-Dark
  # - Default
  # - Default-dark-twilight

# Highlight themes: default, monokai, tomorrow, sunbust. See all on https://highlightjs.org/static/demo/.
highlight_theme: Tomorrow-Night

use_highlight_theme_bg: False

open_dirs: 1 # (int or 'all')

logo: Logo.png



# Show file details in bottom of each file.
# show_file_details: top|bottom|false.

binds:
  search: f
#  switch_raw_rendered: r
