#
# See a detailed list of all settings here:
# https://github.com/xy2z/PineDocs/tree/master#configuration
#

# The title of the
title: PineDocs

# The directory that contains all the content
content_dir: content
# content_dir: P:\Dokumenter

# What logo to show in the top of the menu?
logo: PineDocs--.png

#################
# Optional settings:

index: hey.txt

# Theme to use.
theme:
  # - Wiki
  # - Wiki-Dark
  - Default
  # - Default-twilight

# Code highlighting themes: default, monokai, tomorrow, sunbust, darcula.
# See all on https://highlightjs.org/static/demo/.
highlight_theme: darcula # Tomorrow-Night

# Use transparent bacground on code?
code_transparent_bg: False

# (int or 'all')
open_dirs: 0

# Render the menu footer
render_footer: true

exclude_files:
  - 'index'
  - '/\.yaml/'
