#
# See a detailed list of all settings here:
# https://github.com/xy2z/xyDocs/tree/master##configuration
#

# The title of the
title: xyDocs

# The directory that contains all the content
content_dir: D:\Test\Docs\Dokumenter
# content_dir: P:\Dokumenter

# What logo to show in the top of the menu?
logo: Logo.png

#################
# Optional settings:

index: dude/ay/dude.md

# Theme to use.
theme:
  # - Wiki
  # - Wiki-Dark
  - Default
  - Default-twilight

# Code highlighting themes: default, monokai, tomorrow, sunbust, darcula.
# See all on https://highlightjs.org/static/demo/.
highlight_theme: darcula # Tomorrow-Night

# Use transparent bacground on code?
code_transparent_bg: False

open_dirs: 1 # (int or 'all')

# Render the menu footer
# render_footer: true
