# PineDocs config file.
#
# See a detailed list of all settings here:
# https://github.com/xy2z/PineDocs/tree/master#configuration
#

# The title of the
title: PineDocs

# The full path of the directory that contains all the content files.
# content_dir: content

# What logo to show in the top of the menu?
# logo: my-logo.png

#################
# Optional settings:

index: hey.txt

# Theme to use.
theme: Default

color_scheme: PineDocs

# Code highlighting themes: default, monokai, tomorrow, sunbust, darcula.
# See all on https://highlightjs.org/static/demo/.
highlight_theme: darcula # Tomorrow-Night

# Use transparent bacground on code?
code_transparent_bg: False

# (int or 'all')
open_dirs: 0

# Render the menu footer
render_footer: true

exclude_files:
  - .gits
